#+title: ref_finder.py -- Match references to each sentence in a manuscript
#+author: licjon
#+language: en
#+export_file_name: ref_finder.texi
#+texinfo_dir_category: Emacs
#+texinfo_dir_title: Ref_finder: (ref_finder).
#+texinfo_dir_desc: Match references to each sentence in a manuscript

*  What is Reference Finder?
  :properties:
  :description: Introduction
  :end:
#+cindex: introduction
** Reference Finder will compare each sentence in the manuscript to each reference and help you find which reference supports the sentence in the manuscript as well as provide sentences from each reference that are most likely to give support.
** Essentially, this program takes a text or docx file and compares each sentence to each sentence in multiple PDFs and returns information about what has matched in each PDF, such as:
*** Total words matched
*** The number of individual words matched
*** The frequency of each matched word
*** Numbers matched
*** 1-3 sentences that may closely match the sentence in the given text file. These are determined by:
**** Jaccard similarity
**** Euclidean distance
**** Cosine similarity
** The application I thought of for this program was to find supporting references for a manuscript, hence the name Reference Finder. The manuscript is the text file (.txt) or Word doc file (.docx). References are PDF files. But this can be used for any purpose that requires matching sentences in a text or word file to text in PDFs.
* How to run
:properties:
:custom_id: how-to-run
:description: instructions, commands
:end:
#+cindex: commands

** ref_finder.py is run from the command line. cd into the directory that has ref_finder.py. Your manuscript (txt or docx) and subdirectory of PDFs should be in the same directory but don't have to be.
** Run =python3 ref_finder.py file_name.txt path/to/pdf/folder/=. If your manuscript file is in another directory, then enter the path to the file (including the file name) instead of just the file name.
** After you run it the first time, the PDFs are stored in a json file. If you want to use those references again, you can run the same command but without the path to the references folder. If you have many references stored in the json, but only want to compare select references, use a path to a directory with those references, and it will just use those references (it uses the file names to search for them in the json file).
*** Example of running a docx file in another directory and using all references in the json: =python3 ref_finder.py ~/path/to/file.docx=
** Some optional flags are:
*** --nosave
**** Doesn't save the references to the json file.
**** Even though it doesn't make sense to run this without a file path, it will still run but uses the json file.
**** Example:  =python3 ref_finder.py file.docx ~/path/to/folder/ --nosave=
*** --nodb
**** Doesn't use the json file and reads the PDFs.
**** --nodb will not work unless a filepath is provided.
**** A situation where this could be useful is if you have a large json file but only want to use a few PDFs. It will run faster. 
**** Example:  =python3 ref_finder.py file.txt ~/path/to/folder/ --nodb=
*** --help
* Limitations
** The PDF files must be searchable PDFs. If not, try to use optical character recognition to make a searchable PDF before using Reference Finder. The PDF file format has a broad specification and is not designed for data exchange. This makes PDFs particularly hard to read. Reference Finder used PyPDF2, and if that fails, PDFMiner, and may output a message that the PDF is not readable. Even then, some PDFs will return unreadable garbage (Of the 70 PDFs that I tested, 4 were not readable at all). This will hopefully be addressed in a later version. A possible approach would be to read XML/ePub versions of the articles as XML is machine readable, with the hopes that XML will surpass PDF as the predominant format for online publications.
** False negatives
*** Supporting information that is in a table or graph will probably not be read and matched.
* Provided Example
** Example includes example_manuscript.txt that contains 4 sentences. The PDFs are in the example_refs folder. The folder contains example1.pdf and example2.pdf.
** Download the repository
** Run =python3 ref_finder.py example_manuscript.txt path/to/example_refs/= from the directory ref_finder.py is in 
** The output will be output.txt. Each time the program is run, it will overwrite output.txt.
** Inside output.txt, you will see each sentence in the manuscript, followed by information relating to the references
** Sentence 1
*** The first sentence is an example of some rare undefined behavior in this program. The first time you run this program the Jaccard Similarity will not match. However, run it again and the result derived from the json file will give the matching sentence.
*** The Euclidean distance and Cosine similarity sentences do not match. Sometimes they do, but Jaccard Similarity often returns the best match
*** The example1 also has more word matches than example2
*** The results of example2 show that this reference does not support 
** Sentence 2: Jaccard, Euclidean, and Cosine all match the correct sentence from example1; example2 does not support
** Sentence 3
*** This is another example of less than optimal behavior: example2 has 3 matching sentences even though the scores are lower than normal (Jaccard Index of 0.2 usually does not support). This is probably because another sentence has glommed onto it.  
** Sentence 4 clearly shows strong support from example2
** After running the example, example1 and example2 will be stored into the json. Delete them and leave just the "[]" before running the program with your own files.

